Categories = new Mongo.Collection('categories')
Queries = new Mongo.Collection('queries')
Queries.BlockSearchResults = new Mongo.Collection('BlockSearchResults')
WeatherFeatures = new Mongo.Collection('WeatherFeatures')
MovementFeatures = new Mongo.Collection('MovementFeatures')